name: Run Test Suites

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      test_suite:
        description: 'Test suite to run'
        required: false
        default: 'regression.xml'

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'

    - name: Run Maven tests
      run: mvn test -DsuiteFile=${{ github.event.inputs.test_suite || 'regression.xml' }}
